straw:
  dt: 1.0e-2

  ### field strength
  max_B: 0.5
  ### field extent
  L: 1.0

  layer_bounds: [-5.0, 5.0]
  layer_width: 5
  layer_height: 5
  n_layers: 16
  n_straws: 32

  max_particles: 2
  origin: [0.0, 0.0, -10.0]
  origin_sigma: [1.0, 1.0, 1.0]
  momentum: [0.0, 0.0, 5.0]
  momentum_sigma: [0.25, 0.25, 0.5]
  noise_origin: [0.0, 0.0, -10.0]
  noise_origin_sigma: [1.0, 1.0, 1.0]
  noise_momentum: [0.0, 0.0, 5.0]
  noise_momentum_sigma: [0.25, 0.25, 0.5]
  straw_signal_rate: 100.0
  straw_noise_rate: 20.0